linuxmint/xed

xed/dialogs/xed-close-confirmation-dialog.c

Tested with gtk 3.18.
Before http://i.imgur.com/L2mIAnn.png
After http://i.imgur.com/hk6U6zV.png

xed-close-confirmation-dialog: fix scrolledwindow minimum height

---

xed/xed-notebook.c

whether a tab is being manipulated.  We were just checking
horizontal position, which meant that depending on where you start
a drag-and-drop, it might think you're trying to drag a tab instead,
causing undesirable behavior.

xed-notebook.c: check vertical mouse position when determining

---

configure.ac

Xed is a gtk3 application. We don't need to default to trying to build with gtk2
Fixes https://github.com/linuxmint/xed/issues/23

configure: Don't require passing --with-gtk=3.0 to build

---

xed/xed-window.c

Not sure why this was being done but keep the open tabs visible when swithcing
to fullscreen so you can still access all open tabs

ui: Don't hide the main notebook tabs in fullscreen

---

xed/xed-searchbar.c
xed/xed-searchbar.ui

Currently there is no clear way to close the searchbar. Add a simple small close
button to make this easier.
Closes https://github.com/linuxmint/xed/issues/53

searchbar: Make some improvements

---

xed/xed-preferences-dialog.c

This looks like another old leftover from the move to gtk3
Based on: https://github.com/GNOME/gedit/commit/11fbe0fe146fb60d5f3974fc67fe598361cd02ea
Closes: https://github.com/linuxmint/xed/issues/25

prefs-dialog: Fix a crash when removing style schemes

---

debian/control

We need this for some of the icons being used in the search and status bar.
Closes https://github.com/linuxmint/xed/issues/76

debian: Add a dependency on xapps-common

---

xed/xed-app.c

We were passing the wrong arguments
Based on https://github.com/GNOME/gedit/commit/2e3b5aea0e8810e6946ce4daf64fceea9a9f47a9
Fixes: https://github.com/linuxmint/xed/issues/90

Fix calling set_command_line_wait()

---

xed/xed-commands-file.c

In most cases you want to see the contents of the tab before deciding what to
respond to the dialog that pops up. This is typical behavior in other editors
such as Sublime.
Closes https://github.com/linuxmint/xed/issues/95

Focus a tab when attempting to close it with unsaved changes

---

xed/xed-app-activatable.h
xed/xed-view-activatable.h
xed/xed-window-activatable.h

Fixes the error listed below
```
xed.armv7hl: E: explicit-lib-dependency libpeas-loader-python3(armv7hl-32)
xed.i686: E: explicit-lib-dependency libpeas-loader-python3(x86-32)
xed.x86_64: E: explicit-lib-dependency libpeas-loader-python3(x86-64)
xed-devel.armv7hl: W: no-documentation
xed-devel.armv7hl: E: incorrect-fsf-address /usr/include/xed/xed-window-activatable.h
xed-devel.armv7hl: E: incorrect-fsf-address /usr/include/xed/xed-view-activatable.h
xed-devel.armv7hl: E: incorrect-fsf-address /usr/include/xed/xed-app-activatable.h
xed-devel.i686: W: no-documentation
xed-devel.i686: E: incorrect-fsf-address /usr/include/xed/xed-window-activatable.h
xed-devel.i686: E: incorrect-fsf-address /usr/include/xed/xed-view-activatable.h
xed-devel.i686: E: incorrect-fsf-address …
```

Fix FSF address

---

xed/xed-print-job.c

```
In file included from xed-print-job.c:37:0:
/usr/include/gtksourceview-3.0/gtksourceview/gtksourceprintcompositor.h:28:6: warning: #warning "Only <gtksourceview/gtksource.h> can be included directly." [-Wcpp]
^~~~~~~
In file included from /usr/include/gtksourceview-3.0/gtksourceview/gtksourceprintcompositor.h:35:0,
from xed-print-job.c:37:
/usr/include/gtksourceview-3.0/gtksourceview/gtksourcetypes.h:27:6: warning: #warning "Only <gtksourceview/gtksource.h> can be included directly." [-Wcpp]
^~~~~~~
make[3]: Entering directory '/builddir/build/BUILD/xed-1.4.0/xed'
```

fix gtksourceprintcompositor.h includes warning

---

plugins/filebrowser/xed-file-browser-plugin.c

Change the icon name for the filebrowser from system-file-manager to folder.
This prevents you from getting a weird unexpected icon under some themes
like Mint-Y

filebrowser: Change an icon name

---

xed/xed-window.c

This ensures that the window will be maximized if it was closed in this state.

Use correct value to save the window state in gsettings.

---

po/POTFILES.in

We want the menu entries it provides to be translated but I forgot to add these
when the new plugin was added.

translations: Add the textsize plugin to POTFILES.in

---

plugins/textsize/textsize/documenthelper.py

It seems users can't avoid doing silly things so set a minimum and max font size
for the text zoom function. The numbers chosen here are just arbitrary values I
got from testing. If feedback warrants it, they can be easily changed.

Text zoom: Put a limit on the min and max zoom

---

xed/xed-window.c

Fixes a crash when choosing 'Defaults' as the the highlight language.
Adapted from https://github.com/GNOME/gedit/commit/0434e2f9188cb39b51408859e3e30a8a625b41c6
Closes https://github.com/linuxmint/xed/issues/160

Don't present users with the hidden highlight languages

---

xed/xed-view.c

Two values were swapped in the g_settings_bind() function causing it to look
for a key that didn't exist.
Fixes https://github.com/linuxmint/xed/issues/165

xed-view: Fix a crash when right clicking the left gutter

---

xed/xed-status-combo-box.c

Remove an unneeded frame widget. This cause padding issues in gtk3.22 that
requires overly convoluted theming to get around. This still leaves a few
warnings from the hard coded theming but those can be removed later when we
no longer need to support gtk3.18.

xed-status-combo-box: Simplify the widget heirarchy

---

plugins/textsize/textsize/__init__.py

Fixes
```
/usr/lib64/xed/plugins/textsize/__init__.py:37: PyGIDeprecationWarning: GObject.property is deprecated; use GObject.Property instead
window = GObject.property(type=Xed.Window)
/usr/lib64/xed/plugins/textsize/__init__.py:122: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "name" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
self._action_group = Gtk.ActionGroup("XedTextSizePluginActions")
```

Fix Py*DeprecationWarning

---

plugins/taglist/C.tags.xml.in

Added tags for:
- Including stdio.h
- `include` statements
- The `main` function
- Comments and multi-line comments
- `printf` statements
See issue #187

Add C tags to the taglist plugin

---

plugins/filebrowser/xed-file-browser-plugin.c
plugins/sort/xed-sort-plugin.c
plugins/spell/xed-spell-plugin.c
plugins/wordcompletion/xed-wordcompletion-plugin.c

When building xed 2.0.1, the following warnings were printed:
```
../plugins/filebrowser/xed-file-browser-plugin.c: In function ‘xed_file_browser_plugin_activate’:
../plugins/filebrowser/xed-file-browser-plugin.c:532:22: warning: unused variable ‘schema’ [-Wunused-variable]
GSettingsSchema *schema;
^~~~~~
../plugins/filebrowser/xed-file-browser-plugin.c:531:28: warning: unused variable ‘schema_source’ [-Wunused-variable]
GSettingsSchemaSource *schema_source;
^~~~~~~~~~~~~
../plugins/sort/xed-sort-plugin.c: In function ‘buffer_sort_lines’:
../plugins/sort/xed-sort-plugin.c:168:12: warning: variable ‘last_line’ set but not used [-Wunused-but-set-variable]
gchar *last_line = NULL;
^~~~~~~~~
../plugins/wordcompletion/xed-wordcompletion-plugin.c: In function …
```

Fix warnings when building xed 2.0.1

---

meson.build

This is needed in order to run meson's gnome.yelp() helper when installing the help data.

meson: require itstool command to be available

---

xed/xed-status-menu-button.c

This was broken in https://github.com/linuxmint/xed/commit/7ce2a750dba4af2843786788779498badc72eb41#diff-d114482c8758b92b9c56c95d18efe926

statusbar: Fix the menu button styling

---

xed/xed-print-preview.c

The indices were backwards, which was causing incorrect layout, and scrolling issues at larger zoom levels.

print preview: fix layout drawing for 1X2 and 2X1 layouts

---

plugins/filebrowser/xed-file-browser-view.c
plugins/filebrowser/xed-file-browser-view.h

This is left over code from the gedit days, which we don't use, and don't use. This also has the added benifit of removing at least 1 deprecation warning.

Filebrowser: Kill the click policy property with fire

---

xed/xed-notebook.c

We were only showing the tabs when more than one file was open. When
fullscreen this leaves no indication of the current file having been modified
if there is only one. Instead just set them to show at all times.
Closes: https://github.com/linuxmint/xed/issues/152

xed-notebook: Always show the main notebook tabs

---

xed/xed-print-preview.c

Previously, the logic used to set the sensitivity of the forward navigation button failed to consider when multiple pages are shown. This resulted in the forward button being sensitive in some cases, even if all pages, or the last page were shown. With this commit, it is now updated properly.
Also, when the rows and columns are changed, the current page is now changed to the nearest multiple of rows*cols so that the current page is still shown, but navigating back to the beginning and then forward again will be consistent.

print preview: fix logic for forward button sensitivity

---

xed/resources/css/xed-style.css
xed/resources/ui/xed-shortcuts.ui
xed/resources/ui/xed-ui.xml
xed/xed-commands-edit.c
xed/xed-commands.h
xed/xed-ui.h

Use ctrl+/ for line comments, and ctrl+shift+/ for block comments.
Implements #173

Add toggle comment and toggle comment block actions w/ keybindings

---

xed/xed-print-job.c

Replaces gtk_font_button_*et_font_name with gtk_font_chooser_*et_font

print job: replace some deprecated font button functions

---

plugins/filebrowser/xed-file-browser-widget.c

Also fix a potential memory leak/segfault in the filebrowser plugin.

Replace deprecated gdk_cursor_new with gdk_cursor_new_for_display

---

xed/xed-print-preview.c

This function is no longer needed as the "value-changed" signal is automatically emitted whenever the value changes (since Gtk 3.18).

Print preview: remove a couple calls to gtk_adjustment_value_changed

---

xed/xed-searchbar.c

`gtk_source_search_context_forward_finish`,
`gtk_source_search_context_backward_finish`, and
`gtk_source_search_context_replace`
were replaced with:
`gtk_source_search_context_forward_finish2`,
`gtk_source_search_context_backward_finish2`, and
`gtk_source_search_context_replace2` 
respectively.

Search: replace a few functions that were deprecated in Gtk 3.22

---

xed/xed-window.c

This fixes an issue where moving the mouse along the top edge of the screen while fullscreened will cause a leave event to be triggered, even though the mouse pointer is still inside the event box. This caused the toolbar to disappear and/or stutter while moving the mouse along the top edge.

Fix stuttering and disappearing of the toolbar when fullscreen

---

xed/xed-view-frame.c

This was an override that no longer seems necessary and is causing deprecation warnings.

Remove deprecated call to gtk_widget_override_background_color

---

xed/xed-window-private.h
xed/xed-window.c

This fixes a gdk window assertion error that occurs every time xed is opened, as well as causes the correct menu item to actually be selected as expected (it currently isn't).
The issue was caused by #241 
Fixes #272

Tab width popup: only select a menu item when the menu is open

---

xed/xed-tab.c

The warning was caused by the preview trying to save print settings after the settings object was cleared. Clearing the settings object in *_finalize instead of *_dispose fixes the issue.
Fixes #259

Prevent a warning when closing the window while print preview is open

---

plugins/trailsave/xed-trail-save-plugin.c

The intention was that there should be one empty line left at the end of the file, but the GtkSourceBuffer adds it's own empty line if the implicit_trailing_newline property is true (currently the default behavior in xed), which means we usually end up with 2 lines instead of one. This would change the behavior so that we always end up with no more than one line at the end of the file.
Fixes https://github.com/linuxmint/xed/issues/119

Trailsave plugin: remove second trailing line

---

xed/xed-tab-label.c

It doesn't seem to do anything except intercept scroll events, which are used to switch tabs.
Fixes #120

xed-tab-label.c: remove unused event box preventing scroll events

---

xed/resources/ui/xed-preferences-dialog.ui
xed/xed-preferences-dialog.c

The setting was already available in the schema and implemented in xed itself, but wasn't exposed in the preferences dialog.
Addresses #195

Add settings widget to the prefs dialog for the implicit newline setting

---

xed/resources/ui/xed-shortcuts.ui
xed/xed-ui.h

This PR closes #148. Also added the keyboard shortcut to the list of shortcuts in the Help menu.
I picked "Control R" since "Control W" is already used to close a document. If "Control R" does not suffice as a proper keyboard shortcut, no worries. Let me know what keyboard shortcut would work better and I'll make the change.

Added keyboard shortcut for word wrap.

---

xed/xed-searchbar.c

This PR closes #206 
Added logic that now allows a user to use Replace All across documents without having to re initiate the search over again. 
If anything needs to be changed on this PR, just let me know and I'll make the change accordingly.

Added logic to support using Replace All across documents.

---

xed/xed-highlight-mode-selector.c

Put logic in place to check if the focus needed to be set when the Syntax Highlighting is clicked on in the bottom bar. If it is clicked on before the "View -> Highlight Mode", then the focus is not correctly set in the search text field. 
This closes #332 and closes #274

Added logic to check if the focus need to be set.

---

xed/resources/ui/xed-shortcuts.ui

This PR resolves #307. The shortcuts window can now be displayed along side xed while xed can still be used.
If anything needs to be fixed, changed, or reverted on this PR, just let me know and I'll make the change accordingly.

Changed shortcut window to be non-modal.

---

po/POTFILES.in

@clefebvre You'll have to run makepot after merging this.
See https://postimg.cc/Wtss5vXC mentioned in https://github.com/linuxmint/mint20-beta/issues/25

l10n: add missing strings for new plugin joinlines

---

data/xed.desktop.in.in

This allows you to open a new window with the GWL "New Window" entry
Fixes: https://github.com/linuxmint/xed/issues/393

Add a new window desktop action

---

xed/xed-highlight-mode-dialog.c
xed/xed-highlight-mode-selector.c

Fix a few indentation errors and convert tabs to spaces.

xed-highlight-mode-dialog/selector: Clean up code style

---

help/C/index.docbook

Reading through the help document and noticed some typos, thought I would fix them up. Hopefully this is the right place to do this. I've never contributed to Linux before so bear with me.

Fix various typos in index.docbook

---

xed/xed-commands-view.c
xed/xed-tab.c
xed/xed-window.c

Two crashes are possible:
1. Fixes #450 (toggle overview map without any open tabs/docs)
2. Pressing ESC (e.g. to close searchbar) without any tabs open

Fix crashes when no documents (tabs) are open

---

xed/xed-utils.c
xed/xed-utils.h
xed/xed-view-frame.c

This now handles overflow and underflow correctly, by parsing the string
and then clamping the value between INT_MIN and INT_MAX. `atoi` was
giving us garbage values when the buffer overflowed.
Fixes #408

Uses strtol instead of atoi so that we can properly handle over/underflow.

---

plugins/taglist/meson.build

Avoids unnecessary rebuilds of the taglist plugin's .tags.gz files

meson.build: keep temporary files between builds

---

xed/xed-window.c

fixes the incompatible-pointer-types build warnings

Add missing type cast check

---

xed/xed-window.c

Problem:
Current behavior may result in incorrect window dimensions being saved (as `gtk_widget_get_allocation` doesn't account for window decorations, etc.).
Solution:
Use `gtk_window_get_size` (the recommended GTK function to call for storing window dimensions) to get current dimensions to be saved.

Save correct window size on exit

---

xed/xed-metadata-manager.c

Fix missing include for newer libxml

Update xed-metadata-manager.c - Fix missing include for newer libxml

---

xed/resources/ui/xed-shortcuts.ui
xed/resources/ui/xed-ui.xml
xed/xed-commands-edit.c
xed/xed-commands.h
xed/xed-ui.h
xed/xed-view.c
xed/xed-view.h

By doing CTRL + SHIFT + D the user can duplicate the selection.
Correcting issue #610
If some text is selected, the selection will be duplicated below.
If no text is selected, the line will be duplicated if it has more than 0 characters.

added shortcut to duplicate selection

---

xed/xed-document.c

Added condition to not ask user to save empty documents before closing.
Fixed issue #565 
The function _xed_document_needs_saving will not return true for empty documents.

added condition to not ask user to save empty doc before closing

---

plugins/time/xed-time-plugin.c

Removed line that added a space character after custom date and time insert.
Fixing issue #614
When the user inserts a date and time with a custom format, a trailing space character is added.
The line doing that was removed.

removed trailing space char in custom date time

---

xed/resources/ui/xed-shortcuts.ui
xed/xed-ui.h

To keep with the consistency of using the function keys for toggling windows I mapped F7 to toggle the overview map.
To implement the feature request from issue #623 
Upon using the shortcut the overview map will be toggled similar to how the side and bottom panels work presently.

added shortcut to toggle overview map (#623)

---

xed/xed-notebook.c
xed/xed-tab.c
xed/xed-tab.h

In order to address the issue of the xed program continuing to use computer resources while closing a tab/the application while one or more tabs are in the loading state a new method _xed_tab_cancel_load was created and is called in xed-notebook.
Fixes issue #637 
See video below to show how the new functionality is reflected in the activity monitor:
https://github.com/linuxmint/xed/assets/103229880/a3c0f921-b520-4a20-8005-47dd546c66dd

added method to cancel file loading before closing tab (#637)

---

xed/xed-view.c

This fixes issue #643. When cursor is at the end of the line, old version would duplicate two lines: The line where the cursor is, and the line following it. This happened because the buffer that is being copied would include both lines and the newline separating them. This fix checks if there are multiple lines in the current buffer, and if so, moves buffers end iterator to the newline character, so that only the line where cursor is located is duplicated.

Duplicate only current line when cursor is at the end of the line
