configure.ac
plugins/filebrowser/xed-file-browser-widget.c
xed/Makefile.am
xed/xed-document-input-stream.c
xed/xed-gio-document-loader.c
xed/xed-prefs-manager.c
xed/xed-progress-message-area.c
xed/xed-session.c
xed/xed-smart-charset-converter.c
xed/xed-view.c
xed/xed-window.c

Just like #8 but more complete.

Fix build with gnome-common 3.18

---

xed/xed-close-button.c

Also remove some use of deprecated GtkRcStyle

xed-close-button: Convert to using a symbolic icon

---

plugins/filebrowser/xed-file-browser-view.c
xed/xed-commands-file.c
xed/xed-documents-panel.c
xed/xed-window.c

https://github.com/GNOME/gedit/commit/139db33451057858f196be29f567b7c37140c70b

Focus view when opening files from the filebrowser or documents panel

---

xed/xed-utils.c

This should prevent some crashes under wayland.

xed-utils: Add runtime checks for x11 specific functions

---

plugins/time/xed-time-plugin.c

https://github.com/GNOME/gedit/commit/121f02a3ea066565eeae5dd42868f822ecce4924

time-plugin: Use GDateTime

---

xed/xed-commands-file.c
xed/xed-notebook.c
xed/xed-notebook.h
xed/xed-tab.c
xed/xed-tab.h
xed/xed-window-private.h
xed/xed-window.c

This will help prevent users from inadvertently loosing data when logging out
with unsaved files.
Based on: https://github.com/GNOME/gedit/commit/05918e07ce769606c90488833ebefca9331c97c0

Use GtkApplication inhibit API

---

xed/xed-utils.c

Should fix https://github.com/linuxmint/xed/issues/208
Based on https://github.com/GNOME/gedit/commit/93d1c18c6c4d3dab33add54211224ca41f5c1bf7#diff-0901535af79a747aff62972327ad58ad

Fix clang compile issue

---

xed/resources/ui/xed-ui.xml

Rearrange help entries (xapp consistency)

---

xed/xed-close-confirmation-dialog.c

... for the default actions (save as, save)

close dialog: use "suggested-action" style class

---

xed/xed-window.c

This was broken in the commit that added the new highlight mode selection
dialog. Get it working again.

xed-window: Fix the tabs/spaces label in the statusbar

---

meson.build

Add minimum required version for xapp

---

xed/xed-window.c

Disable the comments action when not supported to avoid confusion

---

help/C/index.docbook

This PR is to fix #251. I could not find a good website to replace the broken link so I removed the link entirely.

Removed link that was not working.

---

xed/xed-app.c

Added logic to free the css file created from the call to `g_file_new_for_uri`. 
If anything needs to be changed or reverted, just let me know and I'll make the changes accordingly. Thanks.

Fixed memory issue found by valgrind

---

help/C/index.docbook

Let me know if anything needs to be changed/updated/reverted and I'll make the changes accordingly.

Cleaned up broken links.

---

data/xed.1
xed/xed-app.c

This PR fixes #284. Added wait entry to man page. Removed logic that cause wait to open extra tab.
Let me know if anything needs to be changed/updated/reverted and I'll make the changes accordingly.

Addressed issue with wait option.

---

plugins/joinlines/joinlines.plugin.desktop.in
plugins/joinlines/joinlines/__init__.py
plugins/joinlines/meson.build
plugins/meson.build
xed/resources/ui/xed-shortcuts.ui

This PR resolves #304.
Made "Join Lines" a builtin plugin. Added shortcut entry to the shortcuts modal for Join Lines. 
If anything needs to be changed, edited, or removed, let me know and I'll make the changes accordingly.

RFT - Created Join Lines plugin

---

plugins/textsize/textsize/documenthelper.py

Currently when zooming text with something selected, only the selected
text is zoomed. There doesn't seem to be any real use for this behavior.
Instead just zoom the full document regardless of selection. This also
simplifies the plugin a good bit.
Closes: https://github.com/linuxmint/xed/issues/327

textsize plugin: Zoom text regardless of selection

---

xed/xed-documents-panel.c
xed/xed-window.c

These are the only two warnings I see during the build.

-Wunused fixups

---

xed/xed-documents-panel.c

Also drop function that is now unused once the previous unused code got removed.

fixup! cleanup: remove code dropped in commit 67892da099357e24b3fd3c31fa758947b1dfc47a

---

debian/control

Not needed anymore since 5d9508d5090e43108614e0095ffb9acf55de21df

remove zenity from dependencies

---

install-scripts/meson.build
install-scripts/meson_install_schemas.py
meson.build

build: add install script for non-debian builds

---

data/meson.build
data/org.x.editor.metainfo.xml.in

Fix and rename appdata file to metainfo
